service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  po-has:
    handler: po-has.handler

    events:
      - http:
          path: partial-order/contains
          method: POST
          cors: true
