service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  get:
    handler: get.handler

    events:
      - http:
          path: unsafe/retrieve
          method: POST
          cors: true
