service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  po-get:
    handler: po-get.handler

    events:
      - http:
          path: partial-order/retrieve
          method: POST
          cors: true
