service: trapeze-example-bad-app

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-2

functions:
  createKey:
    handler: index.createKey
  doSomething:
    handler: index.doSomething
    events:
      - http:
          path: doSomething
          method: post
