service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  has:
    handler: has.handler

    events:
      - http:
          path: unsafe/contains
          method: POST
          cors: true
