service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  po-put:
    handler: to-put.handler

    events:
      - http:
          path: total-order/store
          method: POST
          cors: true
