#!/usr/bin/env bash

time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat1", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat2", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat3", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat4", "image_url" : "https://static.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg", "user" : "catowner", "pass" : "catownerpassword"}' $1
time curl -X POST --data '{"key": "cat5", "image_url" : "https://www.petfinder.com/wp-content/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg", "user" : "catowner", "pass" : "catownerpassword"}' $1
