service: hello-world

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-1

functions:
  put:
    handler: put.handler

    events:
      - http:
          path: unsafe/store
          method: POST
          cors: true
