service: secure-rekognition-analysis-s3-image

frameworkVersion: ">=1.10.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 60
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"   

functions:
  imageAnalysis:
    handler: secure-handler.imageAnalysis
    events:
      - http:
          path: analysis
          method: post    
